# Generated by Django 4.0.3 on 2022-04-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_shippingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shippingPrice',
        ),
        migrations.AddField(
            model_name='order',
            name='shippingPrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
