# Generated by Django 4.0.3 on 2022-04-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_order_shippingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
