# Generated by Django 4.0.3 on 2022-04-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_brand_kids_women'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kids',
            new_name='Kid',
        ),
    ]
