# Generated by Django 4.0.3 on 2022-04-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_accessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
