# Generated by Django 4.0.3 on 2022-04-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_accessories_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='price',
        ),
    ]
