# Generated by Django 4.0.3 on 2022-04-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_accessories_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='brand',
        ),
    ]
