# Generated by Django 4.0.3 on 2022-04-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_product_is_accessories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_accessories',
        ),
        migrations.AddField(
            model_name='product',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.accessories'),
        ),
    ]
