# Generated by Django 4.0.3 on 2022-04-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_product_is_accessories_product_accessories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='status',
        ),
    ]
