# Generated by Django 4.0.3 on 2022-04-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_size_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Women'), ('K', 'Kid')], max_length=2, null=True),
        ),
    ]
