# Generated by Django 4.0.3 on 2022-05-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_orderitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
    ]
